export const SAVE_QUESTIONS = 'SAVE_QUESTIONS';
export const SET_QUESTION_ASKED = 'SET_QUESTION_ASKED';
export const SET_QUESTION_DOWNLOADED = 'SET_QUESTION_DOWNLOADED';

export const QuestionActionsTypes = {
    SAVE_QUESTIONS : 'SAVE_QUESTIONS',
    SET_QUESTION_ASKED : 'SET_QUESTION_ASKED',
    SET_QUESTION_DOWNLOADED : 'SET_QUESTION_DOWNLOADED',
}