
export const SAVE_USER = "SAVE_USER";
export const SAVE_USER_IN_PROGRESS = "SAVE_USER_IN_PROGRESS";
export const SAVE_USER_IN_PROGRESS_ERROR = "SAVE_USER_IN_PROGRESS_ERROR";


interface userActionsInterface {
    SAVE_USER : typeof SAVE_USER,
    SAVE_USER_IN_PROGRESS : typeof SAVE_USER_IN_PROGRESS ,
    SAVE_USER_IN_PROGRESS_ERROR : typeof SAVE_USER_IN_PROGRESS_ERROR,
}


export const userActions : userActionsInterface = {
    SAVE_USER : 'SAVE_USER',
    SAVE_USER_IN_PROGRESS : 'SAVE_USER_IN_PROGRESS',
    SAVE_USER_IN_PROGRESS_ERROR : 'SAVE_USER_IN_PROGRESS_ERROR',
}


